Set filename-friendly snapshot names
rzane/snapshot_testing pull request #1
Opened 2020-02-24 15:37 UTC by thomasklemm

Not in all cases examples are named the way that the description can
immediately be used for as a snapshot filename. In our spec suite
e.g. there's been failures against 0.3.3 when specs are not specifically
named, but have an inferred name.

Chose to go with Rails' String#parameterize since we're using Rails
and it returns well readable strings when testing w/ a few of these
cases, but there might be a more general solution for everyone to use.

Original errors:
```
  1) Failure/Error: (snapshots.keys - visited).grep(/^#{name}\s\d+$/).length
  RegexpError:
    empty char-class: /^is expected to eq []\s\d+$/

  2) Failure/Error: (snapshots.keys - visited).grep(/^#{name}\s\d+$/).length
  RegexpError:
    empty range in char class: /^is expected to have received add_to_menus_catalog([{:caterer_city_names=>["Berlin"], ...]) 1 time\s\d+$/
```

2020-02-24 15:40 UTC, thomasklemm commented
@rzane Thanks for this cool gem, really neat on first experimentations with it 💪 This PR is meant also as a bug report, might not be the best fix for all use-cases and might break existing use, plus doesn't unify file naming across all test frameworks. If you let me know which approach you'd prefer, I can set up a new PR

2020-02-24 16:12 UTC, rzane requested changes
This is a great suggestion, but this will only work for people who have ActiveSupport loaded. And, I'd prefer to not have this gem depend on ActiveSupport.

Instead, would you mind creating a private method `parameterize` and porting that function from ActiveSupport::Inflector?

2020-02-24 16:16 UTC, rzane commented
Actually, the change you made doesn't affect the filename at all. It only affects the name of the actual snapshot, and that shouldn't need to be parameterized. Could you provide a test that demonstrates the problem?

2020-02-25 19:49 UTC, thomasklemm commented
@rzane Your changes in 4a403709315a1c5e6b777ae4314f0e5fc9091706 do the trick, thanks a lot 💪

2020-02-25 19:49 UTC, closed without merging

2020-02-27 12:20 UTC, thomasklemm commented
@rzane If you have the chance, a new release w/ the changes in  https://github.com/rzane/snapshot_testing/commit/4a403709315a1c5e6b777ae4314f0e5fc9091706 would be super amazing! Thanks a lot & sorry for bothering you 🙌

2020-02-28 15:57 UTC, rzane commented
Hey @thomasklemm, I released [v0.3.4](https://rubygems.org/gems/snapshot_testing/versions/0.3.4). Sorry, I forgot to release it!

Thank you for sending the PR! Let me know if you run into any other problems or have any other ideas for features.

2020-02-28 23:01 UTC, thomasklemm commented
Thank you very much @rzane for this new release 🎉